// <auto-generated />
using System;
using LibraryManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260203140943_AddBooks")]
    partial class AddBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Core.Entities.AnalyticsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Timestamp");

                    b.ToTable("AnalyticsLogs");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Genre");

                    b.HasIndex("ISBN");

                    b.HasIndex("Title");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A Handbook of Agile Software Craftsmanship",
                            Genre = "Programming",
                            ISBN = "978-0132350884",
                            Status = "Available",
                            Title = "Clean Code",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 2,
                            Author = "David Thomas, Andrew Hunt",
                            AvailableCopies = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Your Journey to Mastery",
                            Genre = "Programming",
                            ISBN = "978-0135957059",
                            Status = "Available",
                            Title = "The Pragmatic Programmer",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 3,
                            Author = "Gang of Four",
                            AvailableCopies = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elements of Reusable Object-Oriented Software",
                            Genre = "Programming",
                            ISBN = "978-0201633610",
                            Status = "Available",
                            Title = "Design Patterns",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 4,
                            Author = "George Orwell",
                            AvailableCopies = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A dystopian social science fiction novel",
                            Genre = "Fiction",
                            ISBN = "978-0451524935",
                            Status = "Available",
                            Title = "1984",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 5,
                            Author = "Harper Lee",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A novel about racial injustice in the American South",
                            Genre = "Fiction",
                            ISBN = "978-0060935467",
                            Status = "Available",
                            Title = "To Kill a Mockingbird",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 7,
                            Author = "F. Scott Fitzgerald",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 967, DateTimeKind.Utc).AddTicks(9970),
                            Description = "A novel about the American dream and tragedy in the Jazz Age",
                            Genre = "Fiction",
                            ISBN = "978-0743273565",
                            Status = "Available",
                            Title = "The Great Gatsby",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 8,
                            Author = "Jane Austen",
                            AvailableCopies = 5,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 967, DateTimeKind.Utc).AddTicks(9973),
                            Description = "A classic romantic novel about manners and matrimonial machinations",
                            Genre = "Fiction",
                            ISBN = "978-1503290563",
                            Status = "Available",
                            Title = "Pride and Prejudice",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 9,
                            Author = "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
                            AvailableCopies = 2,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 967, DateTimeKind.Utc).AddTicks(9977),
                            Description = "Elements of reusable object?oriented software",
                            Genre = "Programming",
                            ISBN = "978-0201633610",
                            Status = "Available",
                            Title = "Design Patterns (GoF)",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 10,
                            Author = "Kyle Simpson",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 967, DateTimeKind.Utc).AddTicks(9980),
                            Description = "A deep dive into JavaScript’s core mechanisms",
                            Genre = "Programming",
                            ISBN = "978-1098115464",
                            Status = "Available",
                            Title = "You Don't Know JS Yet",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 11,
                            Author = "Cormen, Leiserson, Rivest, Stein",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 967, DateTimeKind.Utc).AddTicks(9984),
                            Description = "Comprehensive algorithms textbook",
                            Genre = "Programming",
                            ISBN = "978-0262033848",
                            Status = "Available",
                            Title = "Introduction to Algorithms (CLRS)",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 12,
                            Author = "Stephen Hawking",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 967, DateTimeKind.Utc).AddTicks(9987),
                            Description = "Exploration of the universe’s origins and structure",
                            Genre = "Science",
                            ISBN = "978-0553380163",
                            Status = "Available",
                            Title = "A Brief History of Time",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 13,
                            Author = "Richard Dawkins",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 967, DateTimeKind.Utc).AddTicks(9991),
                            Description = "Evolutionary biology from a gene?centric view",
                            Genre = "Science",
                            ISBN = "978-0198788607",
                            Status = "Available",
                            Title = "The Selfish Gene",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 14,
                            Author = "Yuval Noah Harari",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 967, DateTimeKind.Utc).AddTicks(9994),
                            Description = "Big history of human species",
                            Genre = "Science",
                            ISBN = "978-0062316097",
                            Status = "Available",
                            Title = "Sapiens: A Brief History of Humankind",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 15,
                            Author = "Thomas S. Kuhn",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 967, DateTimeKind.Utc).AddTicks(9998),
                            Description = "Foundations of paradigm shifts in science",
                            Genre = "Science",
                            ISBN = "978-0226458120",
                            Status = "Available",
                            Title = "The Structure of Scientific Revolutions",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 16,
                            Author = "Rebecca Skloot",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(3),
                            Description = "Story of Henrietta Lacks and HeLa cells",
                            Genre = "Science",
                            ISBN = "978-1400052189",
                            Status = "Available",
                            Title = "The Immortal Life of Henrietta Lacks",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 17,
                            Author = "Jared Diamond",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(44),
                            Description = "Analysis of factors shaping civilizations",
                            Genre = "History",
                            ISBN = "978-0393354324",
                            Status = "Available",
                            Title = "Guns, Germs, and Steel",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 18,
                            Author = "Sun Tzu",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(49),
                            Description = "Ancient military strategy classic",
                            Genre = "History",
                            ISBN = "978-1590302255",
                            Status = "Available",
                            Title = "The Art of War",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 19,
                            Author = "Anne Frank",
                            AvailableCopies = 5,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(235),
                            Description = "Wartime diary of a Jewish girl",
                            Genre = "History",
                            ISBN = "978-0553296983",
                            Status = "Available",
                            Title = "The Diary of Anne Frank",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 20,
                            Author = "Edward Gibbon",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(239),
                            Description = "Classic history of Rome’s fall",
                            Genre = "History",
                            ISBN = "978-0140442106",
                            Status = "Available",
                            Title = "Decline of the Roman Empire",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 21,
                            Author = "Antony Beevor",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(243),
                            Description = "Comprehensive WWII history",
                            Genre = "History",
                            ISBN = "978-0241987091",
                            Status = "Available",
                            Title = "The Second World War",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 22,
                            Author = "Walter Isaacson",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(246),
                            Description = "Biography of Apple co?founder",
                            Genre = "Biography",
                            ISBN = "978-1451648539",
                            Status = "Available",
                            Title = "Steve Jobs",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 23,
                            Author = "Nelson Mandela",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(250),
                            Description = "Autobiography of Nelson Mandela",
                            Genre = "Biography",
                            ISBN = "978-0316548182",
                            Status = "Available",
                            Title = "Long Walk to Freedom",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 24,
                            Author = "Samuel Pepys",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(253),
                            Description = "17th?century English diary",
                            Genre = "Biography",
                            ISBN = "978-0141440644",
                            Status = "Available",
                            Title = "The Diary of Samuel Pepys",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 25,
                            Author = "Walter Isaacson",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(257),
                            Description = "Life of Albert Einstein",
                            Genre = "Biography",
                            ISBN = "978-0743264747",
                            Status = "Available",
                            Title = "Einstein: His Life and Universe",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 26,
                            Author = "Michelle Obama",
                            AvailableCopies = 5,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(261),
                            Description = "Memoir of Michelle Obama",
                            Genre = "Biography",
                            ISBN = "978-1524763138",
                            Status = "Available",
                            Title = "Becoming",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 27,
                            Author = "Agatha Christie",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(265),
                            Description = "Hercule Poirot mystery",
                            Genre = "Mystery",
                            ISBN = "978-0007119318",
                            Status = "Available",
                            Title = "The Murder of Roger Ackroyd",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 28,
                            Author = "Stieg Larsson",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(269),
                            Description = "Thriller novel",
                            Genre = "Mystery",
                            ISBN = "978-0307454546",
                            Status = "Available",
                            Title = "The Girl with the Dragon Tattoo",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 29,
                            Author = "Gillian Flynn",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(274),
                            Description = "Psychological thriller",
                            Genre = "Mystery",
                            ISBN = "978-0307588371",
                            Status = "Available",
                            Title = "Gone Girl",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 30,
                            Author = "Dan Brown",
                            AvailableCopies = 5,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(278),
                            Description = "Conspiracy thriller",
                            Genre = "Mystery",
                            ISBN = "978-0307474278",
                            Status = "Available",
                            Title = "The Da Vinci Code",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 31,
                            Author = "Agatha Christie",
                            AvailableCopies = 5,
                            CreatedAt = new DateTime(2026, 2, 3, 14, 9, 38, 968, DateTimeKind.Utc).AddTicks(281),
                            Description = "Classic locked?room mystery",
                            Genre = "Mystery",
                            ISBN = "978-0062073488",
                            Status = "Available",
                            Title = "And Then There Were None",
                            TotalCopies = 5
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QRCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.SustainabilityMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CarbonFootprintKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("LoanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .IsUnique();

                    b.ToTable("SustainabilityMetrics");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@library.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$0iDzYi4kc5E.H//F2zM3zehgVsVHt3u.bK6jjcR7AWMcIzTx5Z9bi",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "librarian@library.com",
                            Name = "Sizwe Librarian",
                            PasswordHash = "$2a$11$ajhc3F4uJeIv2TYj/YA3.egPR.g8.8fqCxi2IUrj0roGcybbwb/Ou",
                            Role = "Librarian"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patron@library.com",
                            Name = "Luyanda Patron",
                            PasswordHash = "$2a$11$0ThRgPFUjQ5m7e5jt0jp6OHutk.Bhd3xMaLFnGH67.2u6pmuCRUBi",
                            Role = "Patron"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Loan", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Reservation", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.SustainabilityMetric", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Loan", "Loan")
                        .WithOne("SustainabilityMetric")
                        .HasForeignKey("LibraryManagement.Core.Entities.SustainabilityMetric", "LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Book", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Loan", b =>
                {
                    b.Navigation("SustainabilityMetric");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.User", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
